import { BASE, LOGIN, GET_CONFIGURATIONS, PG_CHARGE_WALLET, PG_VERIFY_WALLET, QUICK_PAYMENT } from './urls'
import { PUBLIC_KEY, CUSTOMER, INSURANCE_PUBKEY, DEV_WALLET } from './pie'
export { BASE, LOGIN, GET_CONFIGURATIONS, PG_CHARGE_WALLET, PG_VERIFY_WALLET, QUICK_PAYMENT, PUBLIC_KEY, CUSTOMER, INSURANCE_PUBKEY, DEV_WALLET }